# Generated by Django 3.2.6 on 2021-08-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nigne', max_length=10)),
                ('content', models.CharField(default='', max_length=300)),
                ('slug', models.SlugField(default='nigne', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='English', max_length=20, unique=True)),
                ('code', models.CharField(default='en', max_length=5, unique=True)),
                ('image', models.ImageField(default='images/lang/en-gb.png', null=True, upload_to='images/lang/%Y/%m/%d')),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
