# Generated by Django 3.2.6 on 2021-09-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Egypt', max_length=30)),
                ('name_ar', models.CharField(default='مصر', max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nigne', max_length=10)),
                ('content', models.CharField(default='', max_length=300)),
                ('slug', models.SlugField(default='nigne', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='English', max_length=20, unique=True)),
                ('code', models.CharField(default='en', max_length=5, unique=True)),
                ('image', models.ImageField(default='images/lang/en-gb.png', null=True, upload_to='images/lang/%Y/%m/%d')),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governorates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Qena', max_length=30)),
                ('name_ar', models.CharField(default='قنا', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Qena', max_length=50)),
                ('name_ar', models.CharField(default='Qena', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('governorates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.governorates')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Qena', max_length=30)),
                ('name_ar', models.CharField(default='Qena', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.city')),
            ],
        ),
    ]
