# Generated by Django 3.2.6 on 2021-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_area_city_country_governorates'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_ar',
            field=models.CharField(default='Qena', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(default='Qena', max_length=30),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(default='مصر', max_length=30),
        ),
        migrations.AddField(
            model_name='governorates',
            name='name_ar',
            field=models.CharField(default='قنا', max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='Qena', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Qena', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Egypt', max_length=30),
        ),
        migrations.AlterField(
            model_name='governorates',
            name='name',
            field=models.CharField(default='Qena', max_length=30),
        ),
    ]
