# Generated by Django 3.2.6 on 2021-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('NO', 'NO')], max_length=10),
        ),
    ]
