# Generated by Django 3.2.6 on 2021-09-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='groups',
            new_name='group',
        ),
    ]
