# Generated by Django 3.1.7 on 2021-07-03 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
