# Generated by Django 3.1.7 on 2021-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[], default='en', max_length=6),
        ),
    ]
