# Generated by Django 3.1.7 on 2021-08-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210819_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='position',
            new_name='title',
        ),
    ]
