# Generated by Django 3.1.7 on 2021-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settinglang_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('ar', 'arabic'), ('en', 'english')], max_length=6),
        ),
    ]
