# Generated by Django 3.1.7 on 2021-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210706_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=6),
        ),
    ]
