# Generated by Django 3.1.7 on 2021-06-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210622_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='image',
        ),
    ]
