# Generated by Django 3.1.7 on 2021-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_setting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image',
            field=models.ImageField(default='images/store/nigne.png', upload_to='images/store/'),
        ),
    ]
