# Generated by Django 3.1.7 on 2021-08-18 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_banners_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='position',
            field=models.CharField(choices=[('1', 'Top Left'), ('2', 'Top Middle'), ('3', 'Top Right'), ('4', 'Middle Left'), ('5', 'Middle Right'), ('6', 'Bottom Left'), ('7', 'Bottom Middle'), ('7', 'Bottom Right')], default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
