# Generated by Django 3.1.7 on 2021-08-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banners_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='media_location',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='sort_order',
        ),
    ]
