# Generated by Django 3.1.7 on 2021-08-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210819_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='True', max_length=10),
        ),
    ]
