# Generated by Django 3.2.6 on 2021-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='Province 3', max_length=254)),
                ('district', models.CharField(default='Qena', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='based_on_district',
            field=models.ManyToManyField(blank=True, related_name='delivery_district', to='DeliverySystem.Location'),
        ),
    ]
