# Generated by Django 3.2.6 on 2021-09-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_orderproduct_delivery_by'),
        ('DeliverySystem', '0003_auto_20210912_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='courier',
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.order'),
        ),
    ]
