# Generated by Django 3.1.7 on 2021-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_de',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_tr',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryTranslation',
        ),
    ]
