# Generated by Django 3.1.7 on 2021-07-11 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='product_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='in_stock_total',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_discount_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_long_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_max_price',
        ),
        migrations.AddField(
            model_name='products',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='out_of_stock_status',
            field=models.CharField(choices=[('1', '2-3 Day'), ('2', 'In Stock'), ('3', 'Out Stock'), ('4', 'Pre-order')], default='2', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='requires_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='subtract_stock',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], default='Enable', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producttags',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttags',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttags',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/category/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productquestions',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreviewvoting',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='producttags',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ProductAbout',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products'),
        ),
    ]
