# Generated by Django 3.1.7 on 2021-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
