# Generated by Django 3.1.7 on 2021-06-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Products_description',
            new_name='Product_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Products_long_description',
            new_name='Product_long_description',
        ),
        migrations.RenameField(
            model_name='productsabout',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsdetails',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsmedia',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsquestions',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsreviews',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsreviewvoting',
            old_name='Products_review_id',
            new_name='Product_review_id',
        ),
        migrations.RenameField(
            model_name='productstags',
            old_name='Products_id',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsvarientitems',
            old_name='Products_varient_id',
            new_name='Product_varient_id',
        ),
    ]
