# Generated by Django 3.1.7 on 2021-07-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributesdetails',
            old_name='attribute_detail',
            new_name='attributedetail',
        ),
    ]
