# Generated by Django 3.1.7 on 2021-07-11 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210711_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttags',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='producttags',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='producttags',
            name='title',
        ),
        migrations.AddField(
            model_name='products',
            name='minimum_quantity',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='sort_order',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='producttags',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Meta Tag Title'),
            preserve_default=False,
        ),
    ]
