# Generated by Django 3.1.7 on 2021-08-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionsdetails',
            options={'verbose_name_plural': 'Options Detail'},
        ),
        migrations.AlterModelOptions(
            name='variantdetails',
            options={'verbose_name_plural': 'Variant Detail'},
        ),
        migrations.RenameField(
            model_name='productmedia',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='variantdetails',
            name='variant_image',
            field=models.FileField(blank=True, null=True, upload_to='images/products/%Y/%m/', verbose_name='Product Variant Image'),
        ),
        migrations.AddField(
            model_name='variantdetails',
            name='variant_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributesdetails',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.attributes'),
        ),
        migrations.AlterField(
            model_name='attributesdetails',
            name='attribute_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributesdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products'),
        ),
        migrations.AlterField(
            model_name='optionsdetails',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.options'),
        ),
        migrations.AlterField(
            model_name='optionsdetails',
            name='option_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optionsdetails',
            name='option_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='optionsdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products'),
        ),
        migrations.AlterField(
            model_name='variantdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products'),
        ),
        migrations.AlterField(
            model_name='variantdetails',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.variant'),
        ),
        migrations.AlterField(
            model_name='variantdetails',
            name='variant_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variantdetails',
            name='variant_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
