# Generated by Django 3.1.7 on 2021-08-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantdetails',
            old_name='color',
            new_name='variant_color',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='price',
            new_name='variant_price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='quantity',
            new_name='variant_quantity',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='size',
            new_name='variant_size',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='title',
            new_name='variant_title',
        ),
    ]
