# Generated by Django 3.1.7 on 2021-07-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210729_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributesdetails',
            old_name='attributedetail',
            new_name='attribute_detail',
        ),
    ]
