# Generated by Django 3.2.6 on 2021-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/products/%Y/%m/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
