# Generated by Django 3.1.7 on 2021-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_products_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='long_desc',
            field=models.TextField(null=True),
        ),
    ]
