# Generated by Django 3.1.7 on 2021-07-03 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210703_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(null=models.CharField(max_length=100, unique=True), unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
