# Generated by Django 3.1.7 on 2021-08-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210816_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='ImageVariant',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_title',
            new_name='title',
        ),
    ]
