# Generated by Django 3.1.7 on 2021-07-12 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_products_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='keyword',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
