# Generated by Django 3.1.7 on 2021-07-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210703_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='product',
        ),
    ]
