# Generated by Django 3.1.7 on 2021-08-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_products_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_image',
            new_name='VariantImage',
        ),
    ]
