# Generated by Django 3.1.7 on 2021-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210712_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.FileField(upload_to='images/products/%Y/%m', verbose_name='Store Logo'),
        ),
    ]
