# Generated by Django 3.1.7 on 2021-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210729_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='product_attribute', through='catalog.AttributesDetails', to='catalog.Attributes'),
        ),
        migrations.AddField(
            model_name='products',
            name='attribute_detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='filter',
            field=models.ManyToManyField(blank=True, related_name='product_filter', to='catalog.Filters'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, related_name='product_manufacturer', to='catalog.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_products_related_+', to='catalog.Products'),
        ),
    ]
