# Generated by Django 3.1.7 on 2021-06-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210621_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsabout',
            old_name='Product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsdetails',
            old_name='Product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsmedia',
            old_name='Product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsquestions',
            old_name='Product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsreviews',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='productsreviewvoting',
            old_name='user_voting',
            new_name='user_id_voting',
        ),
        migrations.RenameField(
            model_name='productstags',
            old_name='Product',
            new_name='Product_id',
        ),
        migrations.RenameField(
            model_name='productsvarientitems',
            old_name='Products',
            new_name='Products_id',
        ),
    ]
