# Generated by Django 3.1.7 on 2021-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_filters_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='options',
            name='product',
        ),
    ]
