# Generated by Django 3.1.7 on 2021-08-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210805_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionsdetails',
            old_name='option_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='optionsdetails',
            old_name='option_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='variant_quantity',
            new_name='quantity',
        ),
    ]
