# Generated by Django 3.1.7 on 2021-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210704_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesgroup',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
