# Generated by Django 3.1.7 on 2021-07-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210729_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='attribute_detail',
        ),
    ]
