# Generated by Django 3.1.7 on 2021-07-13 20:57

import catalog.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210713_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.FileField(upload_to=catalog.models.models.image_directory_path, verbose_name='Store Logo'),
        ),
    ]
