# Generated by Django 3.1.7 on 2021-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210704_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10),
        ),
    ]
