# Generated by Django 3.1.7 on 2021-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_products_attribute_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributesdetails',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attributesdetails',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='product_attribute', to='catalog.Attributes'),
        ),
    ]
