# Generated by Django 3.1.7 on 2021-08-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210805_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionsdetails',
            old_name='detail',
            new_name='option_detail',
        ),
        migrations.RenameField(
            model_name='optionsdetails',
            old_name='price',
            new_name='option_price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='detail',
            new_name='variant_detail',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='price',
            new_name='variant_price',
        ),
        migrations.RenameField(
            model_name='variantdetails',
            old_name='quantity',
            new_name='variant_quantity',
        ),
    ]
