# Generated by Django 3.1.7 on 2021-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210713_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.FileField(upload_to=''),
        ),
    ]
