# Generated by Django 3.1.7 on 2021-07-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210713_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/product/%Y/%m'),
        ),
    ]
