# Generated by Django 3.1.7 on 2021-07-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210729_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='optionstype',
            options={'verbose_name_plural': 'Options Type'},
        ),
        migrations.CreateModel(
            name='OptionsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_detail', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('option', models.ManyToManyField(blank=True, related_name='product_attribute', to='catalog.Options')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
            options={
                'verbose_name_plural': 'Options',
            },
        ),
    ]
