# Generated by Django 3.1.7 on 2021-06-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210621_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='vendor',
            new_name='added_by_merchant',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Product_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Products_discount_price',
            new_name='product_discount_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Product_long_description',
            new_name='product_long_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Products_max_price',
            new_name='product_max_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='subcategories_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='update_at',
        ),
    ]
