# Generated by Django 3.1.7 on 2021-06-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210621_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subcategories_id',
            new_name='category',
        ),
    ]
