# Generated by Django 3.1.7 on 2021-07-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210729_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='option_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.optionstype'),
        ),
    ]
