# Generated by Django 3.1.7 on 2021-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_options_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstype',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
