# Generated by Django 3.1.7 on 2021-06-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210621_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='added_by_merchant',
            new_name='seller',
        ),
    ]
