# Generated by Django 3.1.7 on 2021-08-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210821_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title_en',
            new_name='title',
        ),
    ]
