# Generated by Django 3.1.7 on 2021-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210714_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
