# Generated by Django 3.1.7 on 2021-07-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_optionstype_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_type', to='catalog.optionstype'),
        ),
    ]
