# Generated by Django 3.1.7 on 2021-06-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_auto_20210621_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAbout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=255)),
                ('media_content', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_image', models.FileField(upload_to='')),
                ('rating', models.CharField(default='5', max_length=255)),
                ('review', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewVoting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productreviews')),
                ('user_id_voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_product_count', models.IntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[(1, 'BUY'), (2, 'SELL')], max_length=255)),
                ('transaction_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarientItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
        migrations.RemoveField(
            model_name='productsdetails',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productsmedia',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productsquestions',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productsquestions',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='productsreviews',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productsreviews',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='productsreviewvoting',
            name='Product_review_id',
        ),
        migrations.RemoveField(
            model_name='productsreviewvoting',
            name='user_id_voting',
        ),
        migrations.RemoveField(
            model_name='productstags',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productstransaction',
            name='Products_id',
        ),
        migrations.RemoveField(
            model_name='productsvarientitems',
            name='Product_varient_id',
        ),
        migrations.RemoveField(
            model_name='productsvarientitems',
            name='Products_id',
        ),
        migrations.RenameModel(
            old_name='ProductsVarient',
            new_name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='ProductsAbout',
        ),
        migrations.DeleteModel(
            name='ProductsDetails',
        ),
        migrations.DeleteModel(
            name='ProductsMedia',
        ),
        migrations.DeleteModel(
            name='ProductsQuestions',
        ),
        migrations.DeleteModel(
            name='ProductsReviews',
        ),
        migrations.DeleteModel(
            name='ProductsReviewVoting',
        ),
        migrations.DeleteModel(
            name='ProductsTags',
        ),
        migrations.DeleteModel(
            name='ProductsTransaction',
        ),
        migrations.DeleteModel(
            name='ProductsVarientItems',
        ),
        migrations.AddField(
            model_name='productvarientitems',
            name='product_varient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvarient'),
        ),
    ]
