# Generated by Django 3.1.7 on 2021-06-21 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210621_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productabout',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productquestions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productreviews',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productreviewvoting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='url_slug',
        ),
        migrations.RemoveField(
            model_name='producttags',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productabout',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productquestions',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreviews',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreviewvoting',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producttags',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
