# Generated by Django 3.1.7 on 2021-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210621_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10),
        ),
    ]
