# Generated by Django 3.1.7 on 2021-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210714_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sort_order',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
