# Generated by Django 3.1.7 on 2021-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210714_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subtract_stock',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], default='True', max_length=255, null=True),
        ),
    ]
