# Generated by Django 3.1.7 on 2021-06-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210621_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
    ]
