# Generated by Django 3.1.7 on 2021-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210715_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media_content',
            field=models.FileField(upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subtract_stock',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], default='Yes', max_length=255, null=True),
        ),
    ]
