# Generated by Django 3.1.7 on 2021-07-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210715_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='media',
            new_name='Image',
        ),
    ]
