# Generated by Django 3.2.6 on 2021-09-22 01:43

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=' ', max_length=150)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Vendor Email')),
                ('phone', models.IntegerField(default='510', verbose_name='Vendor Phone')),
                ('company', models.CharField(default=' ', max_length=50)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('keywords', models.CharField(default=' ', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('youtube', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('activation', models.BooleanField(default=False)),
                ('code', models.CharField(editable=False, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.area')),
                ('city', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='localization.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.country')),
                ('governorates', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='localization.governorates')),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_content', models.FileField(upload_to=vendors.models.image_directory_path, verbose_name='Vendor Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
