# Generated by Django 3.2.6 on 2021-08-29 20:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nigne', max_length=150, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True, verbose_name='Store Email')),
                ('phone', models.IntegerField(blank=True, default='510', verbose_name='Store Phone')),
                ('company', models.CharField(default=' ', max_length=50, null=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('keywords', models.CharField(default=' ', max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('youtube', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('activation', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_content', models.FileField(upload_to=vendors.models.image_directory_path, verbose_name='Store Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.store')),
            ],
        ),
    ]
