# Generated by Django 3.1.7 on 2021-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(default='Nigne', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Store Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.IntegerField(blank=True, default='510', verbose_name='Store Phone'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='False', max_length=10),
        ),
    ]
