# Generated by Django 3.1.7 on 2021-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20210707_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
