# Generated by Django 3.2.6 on 2021-08-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemedia',
            name='media_type',
        ),
    ]
