# Generated by Django 3.2.6 on 2021-09-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0005_alter_language_status'),
        ('vendors', '0002_auto_20210916_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.area'),
        ),
    ]
