# Generated by Django 3.2.6 on 2021-09-16 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='code',
            field=models.CharField(auto_created=True, default=django.utils.timezone.now, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
