# Generated by Django 3.1.7 on 2021-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20210707_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
