# Generated by Django 3.1.7 on 2021-07-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_store_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contact',
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
