# Generated by Django 3.2.6 on 2021-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
