# Generated by Django 3.1.7 on 2021-07-08 03:43

from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210708_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=255)),
                ('media_content', models.FileField(upload_to=vendors.models.image_directory_path, verbose_name='Store Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='vendors.store')),
            ],
        ),
    ]
