# Generated by Django 3.1.7 on 2021-07-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_storemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
    ]
