# Generated by Django 3.1.7 on 2021-07-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20210708_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemedia',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.store'),
        ),
    ]
