# Generated by Django 3.2.6 on 2021-09-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraddress_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='location_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Business', 'Business')], max_length=10),
        ),
    ]
