# Generated by Django 3.2.6 on 2021-08-29 02:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('_groups', django.db.models.manager.Manager()),
            ],
        ),
    ]
