# Generated by Django 3.1.7 on 2021-08-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210802_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='apartment',
        ),
    ]
