# Generated by Django 3.1.7 on 2021-08-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_useraddress_apartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='Shipping_note',
            new_name='shipping_note',
        ),
    ]
