# Generated by Django 3.1.7 on 2021-08-02 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210802_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
