# Generated by Django 3.2.6 on 2021-09-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='note',
        ),
    ]
