# Generated by Django 3.2.6 on 2021-09-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='slug',
            field=models.SlugField(blank=True, default='COD', max_length=128, null=True),
        ),
    ]
