# Generated by Django 3.1.7 on 2021-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shopcart_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
