# Generated by Django 3.2.6 on 2021-08-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('catalog', '0002_initial'),
        ('sales', '0003_remove_shopcart_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.store'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.products'),
        ),
    ]
