# Generated by Django 3.2.6 on 2021-09-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliverySystem', '0003_auto_20210912_1942'),
        ('sales', '0003_auto_20210912_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_person_ip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_taken_datetime',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_delivery_person', to='DeliverySystem.courier'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_person_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_taken_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
