# Generated by Django 3.2.6 on 2021-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210915_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/payment_method/%Y/%m/%d'),
        ),
    ]
