# Generated by Django 3.2.6 on 2021-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_paymentmethods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Online Payment', 'Online Payment'), ('Cash on delivery', 'Cash on delivery')], default='Pending', max_length=100),
        ),
    ]
