# Generated by Django 3.2.6 on 2021-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210912_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='delivery_by',
            field=models.CharField(choices=[('True', 'Ydoob'), ('False', 'Self')], default='False', max_length=10),
        ),
    ]
