# Generated by Django 3.2.6 on 2021-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='slug',
            field=models.SlugField(default='nigne', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'NO')], default='False', max_length=10),
        ),
    ]
